### ISSUE TITLE
Worker launch command contains references to non-existent & invalid directories

### ISSUE THREAD

**Issue by dsKarthick** [mesos/storm#107] opened 2016-03-16 22:06 UTC
Commit I am working on:
    https://github.com/mesos/storm/commit/a49e8ce1af34969daf0479b09ce7a741e181d4ef

Actions:
   * vagrant up
   * start nimbus
   * submit a topology

Problem:
    Following is the ps output of a running worker. The directories like `/mnt/mesos/sandbox/logs`, `/opt/storm/lib/`, etc. do not exist. 

```
root     12914  5.8  7.0 2963108 285176 ?      Sl   17:36  15:19 /usr/lib/jvm/java-7-openjdk-amd64/bin/java -server -Xmx384m -XX:+PrintGCDetails -Xloggc:artifacts/gc.log -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump -Djava.library.path=storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources/Linux-amd64:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources:/usr/local/lib:/opt/local/lib:/usr/lib -Dlogfile.name=worker-31000.log -Dstorm.home=/opt/storm -Dstorm.conf.file= -Dstorm.options=storm.log.dir%3D%2Fmnt%2Fmesos%2Fsandbox%2Flogs -Dstorm.log.dir=/mnt/mesos/sandbox/logs -Dlogback.configurationFile=/opt/storm/logback/cluster.xml -Dstorm.id=SampleTopology-1-1458074947 -Dworker.id=869a17ff-9121-432b-bd43-ae4dfec81ef0 -Dworker.port=31000 -cp /opt/storm/lib/commons-io-2.4.jar:/opt/storm/lib/commons-codec-1.6.jar:/opt/storm/lib/commons-exec-1.1.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/storm-core-0.9.6.jar:/opt/storm/lib/disruptor-2.10.4.jar:/opt/storm/lib/commons-fileupload-1.2.1.jar:/opt/storm/lib/ring-core-1.1.5.jar:/opt/storm/lib/json-simple-1.1.jar:/opt/storm/lib/clj-stacktrace-0.2.2.jar:/opt/storm/lib/tools.macro-0.1.0.jar:/opt/storm/lib/math.numeric-tower-0.0.1.jar:/opt/storm/lib/jetty-6.1.26.jar:/opt/storm/lib/tools.logging-0.2.3.jar:/opt/storm/lib/asm-4.0.jar:/opt/storm/lib/commons-lang-2.5.jar:/opt/storm/lib/ring-jetty-adapter-0.3.11.jar:/opt/storm/lib/clout-1.0.1.jar:/opt/storm/lib/core.incubator-0.1.0.jar:/opt/storm/lib/carbonite-1.4.0.jar:/opt/storm/lib/logback-classic-1.0.13.jar:/opt/storm/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/lib/jgrapht-core-0.9.0.jar:/opt/storm/lib/tools.cli-0.2.4.jar:/opt/storm/lib/ring-servlet-0.3.11.jar:/opt/storm/lib/chill-java-0.3.5.jar:/opt/storm/lib/hiccup-0.3.6.jar:/opt/storm/lib/objenesis-1.2.jar:/opt/storm/lib/clojure-1.5.1.jar:/opt/storm/lib/snakeyaml-1.11.jar:/opt/storm/lib/kryo-2.21.jar:/opt/storm/lib/storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:/opt/storm/lib/joda-time-2.0.jar:/opt/storm/lib/ring-devel-0.3.11.jar:/opt/storm/lib/commons-logging-1.1.3.jar:/opt/storm/lib/minlog-1.2.jar:/opt/storm/lib/servlet-api-2.5.jar:/opt/storm/lib/compojure-1.1.3.jar:/opt/storm/lib/slf4j-api-1.7.5.jar:/opt/storm/lib/logback-core-1.0.13.jar:/opt/storm/lib/jetty-util-6.1.26.jar:/opt/storm/lib/clj-time-0.4.1.jar:/opt/storm/lib/jline-2.11.jar:/opt/storm/conf:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/stormjar.jar backtype.storm.daemon.worker SampleTopology-1-1458074947 master 31000 869a17ff-9121-432b-bd43-ae4dfec81ef0
```

And making that readable instead of 1 fat line:
```
% echo '/usr/lib/jvm/java-7-openjdk-amd64/bin/java -server -Xmx384m -XX:+PrintGCDetails -Xloggc:artifacts/gc.log -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump -Djava.library.path=storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources/Linux-amd64:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources:/usr/local/lib:/opt/local/lib:/usr/lib -Dlogfile.name=worker-31000.log -Dstorm.home=/opt/storm -Dstorm.conf.file= -Dstorm.options=storm.log.dir%3D%2Fmnt%2Fmesos%2Fsandbox%2Flogs -Dstorm.log.dir=/mnt/mesos/sandbox/logs -Dlogback.configurationFile=/opt/storm/logback/cluster.xml -Dstorm.id=SampleTopology-1-1458074947 -Dworker.id=869a17ff-9121-432b-bd43-ae4dfec81ef0 -Dworker.port=31000 -cp /opt/storm/lib/commons-io-2.4.jar:/opt/storm/lib/commons-codec-1.6.jar:/opt/storm/lib/commons-exec-1.1.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/storm-core-0.9.6.jar:/opt/storm/lib/disruptor-2.10.4.jar:/opt/storm/lib/commons-fileupload-1.2.1.jar:/opt/storm/lib/ring-core-1.1.5.jar:/opt/storm/lib/json-simple-1.1.jar:/opt/storm/lib/clj-stacktrace-0.2.2.jar:/opt/storm/lib/tools.macro-0.1.0.jar:/opt/storm/lib/math.numeric-tower-0.0.1.jar:/opt/storm/lib/jetty-6.1.26.jar:/opt/storm/lib/tools.logging-0.2.3.jar:/opt/storm/lib/asm-4.0.jar:/opt/storm/lib/commons-lang-2.5.jar:/opt/storm/lib/ring-jetty-adapter-0.3.11.jar:/opt/storm/lib/clout-1.0.1.jar:/opt/storm/lib/core.incubator-0.1.0.jar:/opt/storm/lib/carbonite-1.4.0.jar:/opt/storm/lib/logback-classic-1.0.13.jar:/opt/storm/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/lib/jgrapht-core-0.9.0.jar:/opt/storm/lib/tools.cli-0.2.4.jar:/opt/storm/lib/ring-servlet-0.3.11.jar:/opt/storm/lib/chill-java-0.3.5.jar:/opt/storm/lib/hiccup-0.3.6.jar:/opt/storm/lib/objenesis-1.2.jar:/opt/storm/lib/clojure-1.5.1.jar:/opt/storm/lib/snakeyaml-1.11.jar:/opt/storm/lib/kryo-2.21.jar:/opt/storm/lib/storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:/opt/storm/lib/joda-time-2.0.jar:/opt/storm/lib/ring-devel-0.3.11.jar:/opt/storm/lib/commons-logging-1.1.3.jar:/opt/storm/lib/minlog-1.2.jar:/opt/storm/lib/servlet-api-2.5.jar:/opt/storm/lib/compojure-1.1.3.jar:/opt/storm/lib/slf4j-api-1.7.5.jar:/opt/storm/lib/logback-core-1.0.13.jar:/opt/storm/lib/jetty-util-6.1.26.jar:/opt/storm/lib/clj-time-0.4.1.jar:/opt/storm/lib/jline-2.11.jar:/opt/storm/conf:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/stormjar.jar backtype.storm.daemon.worker SampleTopology-1-1458074947 master 31000 869a17ff-9121-432b-bd43-ae4dfec81ef0' | tr ' ' '\n'
/usr/lib/jvm/java-7-openjdk-amd64/bin/java
-server
-Xmx384m
-XX:+PrintGCDetails
-Xloggc:artifacts/gc.log
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=10
-XX:GCLogFileSize=1M
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=artifacts/heapdump
-Djava.library.path=storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources/Linux-amd64:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/resources:/usr/local/lib:/opt/local/lib:/usr/lib
-Dlogfile.name=worker-31000.log
-Dstorm.home=/opt/storm
-Dstorm.conf.file=
-Dstorm.options=storm.log.dir%3D%2Fmnt%2Fmesos%2Fsandbox%2Flogs
-Dstorm.log.dir=/mnt/mesos/sandbox/logs
-Dlogback.configurationFile=/opt/storm/logback/cluster.xml
-Dstorm.id=SampleTopology-1-1458074947
-Dworker.id=869a17ff-9121-432b-bd43-ae4dfec81ef0
-Dworker.port=31000
-cp
/opt/storm/lib/commons-io-2.4.jar:/opt/storm/lib/commons-codec-1.6.jar:/opt/storm/lib/commons-exec-1.1.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/storm-core-0.9.6.jar:/opt/storm/lib/disruptor-2.10.4.jar:/opt/storm/lib/commons-fileupload-1.2.1.jar:/opt/storm/lib/ring-core-1.1.5.jar:/opt/storm/lib/json-simple-1.1.jar:/opt/storm/lib/clj-stacktrace-0.2.2.jar:/opt/storm/lib/tools.macro-0.1.0.jar:/opt/storm/lib/math.numeric-tower-0.0.1.jar:/opt/storm/lib/jetty-6.1.26.jar:/opt/storm/lib/tools.logging-0.2.3.jar:/opt/storm/lib/asm-4.0.jar:/opt/storm/lib/commons-lang-2.5.jar:/opt/storm/lib/ring-jetty-adapter-0.3.11.jar:/opt/storm/lib/clout-1.0.1.jar:/opt/storm/lib/core.incubator-0.1.0.jar:/opt/storm/lib/carbonite-1.4.0.jar:/opt/storm/lib/logback-classic-1.0.13.jar:/opt/storm/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/lib/jgrapht-core-0.9.0.jar:/opt/storm/lib/tools.cli-0.2.4.jar:/opt/storm/lib/ring-servlet-0.3.11.jar:/opt/storm/lib/chill-java-0.3.5.jar:/opt/storm/lib/hiccup-0.3.6.jar:/opt/storm/lib/objenesis-1.2.jar:/opt/storm/lib/clojure-1.5.1.jar:/opt/storm/lib/snakeyaml-1.11.jar:/opt/storm/lib/kryo-2.21.jar:/opt/storm/lib/storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:/opt/storm/lib/joda-time-2.0.jar:/opt/storm/lib/ring-devel-0.3.11.jar:/opt/storm/lib/commons-logging-1.1.3.jar:/opt/storm/lib/minlog-1.2.jar:/opt/storm/lib/servlet-api-2.5.jar:/opt/storm/lib/compojure-1.1.3.jar:/opt/storm/lib/slf4j-api-1.7.5.jar:/opt/storm/lib/logback-core-1.0.13.jar:/opt/storm/lib/jetty-util-6.1.26.jar:/opt/storm/lib/clj-time-0.4.1.jar:/opt/storm/lib/jline-2.11.jar:/opt/storm/conf:storm-local/supervisor/stormdist/SampleTopology-1-1458074947/stormjar.jar
backtype.storm.daemon.worker
SampleTopology-1-1458074947
master
31000
869a17ff-9121-432b-bd43-ae4dfec81ef0
```

**Comment by erikdw** [comment] 2016-03-21 23:50
I believe this is specific to using the Docker image option, since the `/opt/storm` path only is referenced by the `Dockerfile` in this repo:
```
% git grep /opt
Dockerfile:  mkdir -p /opt/storm && \
Dockerfile:  tar xf storm-mesos-*.tgz -C /opt/storm --strip=1 && \
Dockerfile:WORKDIR /opt/storm
```

**Comment by erikdw** [comment] 2016-04-18 04:11
@dsKarthick :  I'm still unsure what the issue is here. 

 The docker images I've looked at *do* have `/opt/storm/lib`.

Also, regarding `storm.log.dir`, it just uses the MESOS_SANDBOX environment variable that is set explicitly by mesos's docker containerizer code:
```
(mesos) [tags/0.22.1] % git grep MESOS_SANDBOX
docs/docker-containerizer.md:3, Run the docker image with the configured DockerInfo options, and map the sandbox directory into the Docker container and set the directory mapping to the MESOS_SANDBOX environment variable.
src/docker/docker.cpp:  argv.push_back("MESOS_SANDBOX=" + mappedDirectory);
```

So I'm closing this for now.  Please reopen if you have more info.

**Closed by erikdw** 2016-04-18 04:11 UTC
Labels: bug, docker, invalid
