### ISSUE TITLE
Storm 1.0.0 Support

### ISSUE THREAD

**Issue by DarinJ** [mesos/storm#128] opened 2016-04-12 18:31 UTC
Storm 1.0.0 just landed, I'm exploring what it'll take to get it running on Mesos.  Not sure the level of difficulty in this, but thought I'd open the thread.

**Comment by DarinJ** [comment] 2016-04-12 19:52
Spent a little time, and I got it to compile with 1.0.0, fortunately all issues with the executable code are changes to packages names `s/backtype/org.apache/g`.

Unfortunately, the tests are a little more broken as a few constructors are broken.

Open to suggestions.

**Comment by erikdw** [comment] 2016-04-12 20:15
@DarinJ : Can you please push a branch with the refactor you did so far?   Tried some sed'ing like you suggested, but have a bunch of issues still.

**Comment by DarinJ** [comment] 2016-04-12 20:40
@erikdw take a look at https://github.com/DarinJ/storm/tree/1.0.0-WIP, I'm not at a box with git right now but I can push to a like branch later.  `STORM_RELEASE=1.0.0 ./bin/build-release.sh mvnPackage` compiles but 5 tests fail, I'm also quite certain I broke 0.9.x 💣 and 0.10.x 💥.

**Comment by erikdw** [comment] 2016-04-13 00:06
Sigh, `1.0` is a big PITA :(   ...  I *have* to retain support for `0.9.x`, so I have no idea how to support `1.0+` in the same code, without a bunch more shims (e.g., `MesosNimbus` implements either `backtype.storm.scheduler.INimbus` OR `org.apache.storm.scheduler.INimbus`).  Keeping 2 separate branches and porting changes seems decidedly unfun.

**Comment by DarinJ** [comment] 2016-04-13 01:16
Yeah a few c style ifdefs would be awesome right now :(.  I'm also mostly still 0.9.6 now and only testing 0.10.x.  I'll look into it some more later but thought I'd start the conversation.

**Comment by erikdw** [comment] 2016-04-13 01:27
@DarinJ : so I got the tests to work for `storm-1.0.0` based on your branch with a number of changes.  Main changes:
* change "config maps" from `Map<String, TopologyDetails>` type (which is just *wrong*) to just `Map`.
* add in a couple of keys that are required by TopologyDetails via asserts now:
 * `topologyConf.put("topology.worker.max.heap.size.mb", 768.0);`
 * `topologyConf.put("topology.priority", 0);`
* change some constructor arguments:
 * removed null in `SupervisorDetails` case
 * added extra param in `Cluster` case (this one is also storm-1.0+ specific)

**Comment by erikdw** [comment] 2016-04-13 02:16
Here's the MesosNimbus and ui running on storm-1.0.0:
-----
_Haven't yet rebuilt a topology and tried launching it_

<img width="1440" alt="screenshot 2016-04-12 19 13 37" src="https://cloud.githubusercontent.com/assets/1111441/14480957/f4e8864e-00e2-11e6-8208-77a7e8d1b87f.png">

**Comment by erikdw** [comment] 2016-04-13 02:28
Here's proof of the MesosSupervisor and worker running on storm-1.0.0:
------
<img width="1440" alt="screenshot 2016-04-12 19 27 51" src="https://cloud.githubusercontent.com/assets/1111441/14481124/c8b91992-00e4-11e6-84c0-273ac3f94ebb.png">

**Comment by DarinJ** [comment] 2016-04-13 02:29
@erikdw you've been busy! Thanks, I'll check it out tomorrow.

**Comment by salimane** [comment] 2016-04-13 05:53
@erikdw 👍  very nice. Great Job :)

For the support , we can decide to make storm-mesos 0.2.0 compatible only with storm 1.0.0 and then remove  all the code from 0.9.x  and 0.10.x. That would clean up a lot of things and be leaner.
What do you guys think ?

What about HA from storm 1.0.0, have you done anything there ?

I'm very excited for storm 1.0.0 :)

Thanks

**Comment by erikdw** [comment] 2016-04-13 06:18
@salimane : Thanks!   Regarding rev'ing the project up to 0.2.0 or 1.0 or something and dropping earlier storm version support:  unfortunately, I still have some things I wanna updatein storm-mesos running on storm-0.9.x before declaring it "done".  Specifically, we have some changes for the slot scheduling that greatly improve it's handling of corner cases.  Sadly, we cannot focus on getting those in yet, because we're in the midst of a large revamp to get off of a hacky fork onto this OSS project.  As soon as we get that in a solid state we'll come back to fixing the scheduler.  Also, given what I've revealed before (having dozens of teams with their own topology code that *all* needs to be updated for storm-1.0), just dropping 0.9.x and moving to storm-1.0 is going to require a ton of coordination, so it's not something we can do at the drop of a hat.

@salimane & @DarinJ : I was thinking about how to handle this huge deviation with storm-1.0 renaming the package paths (`backtype` -> `org.apache`), and it _might_ not be *toooooo* bad to do some shim-ish stuff to move the INimbus and ISupervisor into `storm-shim-{9,1,10}x` modules and just leave their meat in the generic module.  `INimbusInterfaceShimClassRedirectorWrapperThingy`! Sigh.

The alternative would appear to be an extension of @salimane 's proposal:  create separate release trains on separate branches, with 0.1.x being left as the one that storm-0.9.x & storm-0.10.x are built for, and master becoming "latest" for now.  The implication is that we'll have to selectively backport changes to the 0.1.x branch.  Though that sucks, it might be easier and less dirty long-term than the horrible hackishness I just proposed in the previous paragraph.

**Comment by erikdw** [comment] 2016-04-13 06:20
@salimane : also, regarding this question:
> What about HA from storm 1.0.0, have you done anything there ?

Nope, haven't done anything, except notice the interesting thing in the screenshot of the Storm UI:  2 Nimbuses sitting there!

**Comment by salimane** [comment] 2016-04-13 06:27
@erikdw,  yep as you said in the second paragraph, we can still do minor update to storm-mesos 0.1.x and have 0.1.1, 0.1.2... etc.

Then 0.2.0 would be only for storm 1.0.0 +

**Comment by erikdw** [comment] 2016-04-13 06:28
Oh, and the fact that the travis deploy integration is based on the git tag should allow us to trivially continue making releases from each branch (0.1.x and master) right?

**Comment by salimane** [comment] 2016-04-13 08:18
yep exactly, you are right :)

**Comment by DarinJ** [comment] 2016-04-28 01:37
@erikdw We've been playing with our mod's a bit which ended up working pretty well. While we're not in a hurry to jump to storm 1.0.0, we'll probably skip 0.10.X and jump to 1.0.0.  I'll explore the option of shim v branch to see if it's worth while, though I'm not optimistic with the number of method signatures that changed in the unit tests.

There are still a number of additional things that should be addressed wrt 1.0.0 such as does HA nimbus just work and should we launch a pace maker and if so how should it be handled wrt service discovery.

I'll probably start work in a couple weeks as I'm currently on a different project unless someone beats me to it.

**Comment by erikdw** [comment] 2016-04-29 01:56
@DarinJ : sounds good, we're also busy for the moment.  And I'm also excited to figure out how to get HA Nimbus working directly on Mesos.  Regarding "pacemaker" (the hearbeat handling server) I remember reading something, but I'm not familiar yet.  I *assume* we should set it up too... but don't "know" for sure.

**Comment by salimane** [comment] 2016-05-31 12:42
any update on this ? :(

**Comment by DarinJ** [comment] 2016-05-31 14:12
@salimane not really I planned to do some work this weekend but decided to go strawberry picking instead.  Hoping to get to it soon.  Definitely going with a separate branch though, I determined shims were to much work.

**Comment by erikdw** [comment] 2016-05-31 22:06
@salimane & @DarinJ : yeah, branches seem the way to go.  I have work time allocated for this during the next 2 weeks, so I'll work on it.

Here's the proposal:

1. `master` branch:
   * will be for `storm-1.0`+, because it has the package path change (`backtype` to `org.apache`)
   * will remove the shim modules and code
2. `storm-0.x` branch:
   * will be for `storm-0.9.x` and `storm-0.10.x`.
   * will retain the shims

**Comment by erikdw** [comment] 2016-06-19 06:21
FYI, I'm holding off working on the branch-split until @dsKarthick 's big change in PR #146 lands, since it's a bunch of code.  We'll then let it bake for a week or so in our staging environment, after which I will proceed to perform this split and we can start iterating on storm-1.0+ support in the master branch.

**Comment by handmail** [comment] 2016-07-20 10:14
@erikdw I built Storm 1.0 and mesos 0.28.2 , but failure . 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project storm-mesos: Compilation failure: Compilation failure:

**Comment by erikdw** [comment] 2016-07-20 19:30
@handmail : yes, that is fully expected -- as discussed above, the issue is that the storm project changed their base package path from `backtype` to `org.apache`.  I'm still wrestling with #154 and need that fixed before I do the breaking change proposed above.

**Comment by zhanghangchina** [comment] 2016-08-11 09:25
@erikdw when I built Storm 1.0 and mesos 0.28.2,meet a problem.
 It says "Failed to detect a master: Failed to parse data of unknown label 'json.info'" when it connects to zookeeper.

**Comment by zhanghangchina** [comment] 2016-08-11 09:26
@erikdw 
how to solve th problem?

**Comment by zhanghangchina** [comment] 2016-08-11 09:27
@erikdw 
how to solve the problem?

**Comment by erikdw** [comment] 2016-08-16 04:32
@zhanghangchina : (I deleted the redundant message you posted".

Can you clarify where you read this message?  (I am not sure you you mean by "It says").
Let's talk about this separately, I don't wanna spoil this (#128) with this tangent, which is likely to be something related to your setup, 'cause I have used this stuff just fine myself.  So like I said in PR #167, please open an issue.

**Comment by erikdw** [comment] 2016-10-31 04:41
@DarinJ @zhanghangchina @salimane : I finally completed some of my professional responsibilities that were preventing me from getting to this -- so I'm working on PR #177 to add this support for Storm 1.0+ into the master branch.

**Comment by salimane** [comment] 2016-10-31 07:27
@awesome !

**Comment by erikdw** [comment] 2016-11-05 22:28
Complete.  See releases here:
* https://github.com/mesos/storm/releases/tag/v0.2.0
* https://hub.docker.com/r/mesos/storm/tags/

**Closed by erikdw** 2016-11-05 22:28 UTC
Labels: build, enhancement
