### ISSUE TITLE
'stormconf.ser' does not exist

### ISSUE THREAD

**Issue by abhishekamralkar** [mesos/storm#89] opened 2016-01-29 19:49 UTC
I am getting below error 

```
2016-01-29 19:47:50.893 b.s.d.worker [ERROR] Error on initialization of server mk-worker
java.io.FileNotFoundException: File '/data/mesos/work/slaves/58476bf6-6b41-4907-be4e-adf496595597-S10/frameworks/58476bf6-6b41-4907-be4e-adf496595597-0015/executors/word-count-2-1454096852/runs/2e3e1455-4960-44ca-97da-937259c25364/storm-mesos/storm-local/supervisor/stormdist/word-count-2-1454096852/stormconf.ser' does not exist
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.readFileToByteArray(FileUtils.java:1763) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.config$read_supervisor_storm_conf.invoke(config.clj:222) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.worker$fn__7098$exec_fn__1236__auto____7099.invoke(worker.clj:418) ~[storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:178) ~[clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
	at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7098$mk_worker__7175.doInvoke(worker.clj:409) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:542) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
2016-01-29 19:47:50.900 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:336) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$fn__7098$mk_worker__7175.doInvoke(worker.clj:409) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:512) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker$_main.invoke(worker.clj:542) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:165) [clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.worker.main(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
```

Any idea why this happening? This is old Storm bug but it got fixed in 0.9.3 version.

**Comment by erikdw** [comment] 2016-01-31 22:43
@abhishekamralkar : storm can be really noisy, emitting misleading/red-herring errors.  The above could happen when a worker takes awhile to come up and the nimbus reassigns the worker to another port or host/supervisor.  You should debug the timing of those logs w.r.t. when the nimbus is doing the assignments of storm executors onto slots.

**Comment by abhishekamralkar** [comment] 2016-02-01 05:24
@erikdw : Do you mean to say Mesos is not able to allocate resource properly , or is there way we can increase timeout , redistribution / reassign the worker .

I am getting the same error when I using docker instead mesos uri's.

**Comment by dsKarthick** [comment] 2016-02-01 05:38
@abhishekamralkar Yours might be related to [STORM-130](https://issues.apache.org/jira/browse/STORM-130). You could try reproducing the bug by following the steps listed in the ticket. But in general, it looks to me like, the exception results from an improper cleanup.

**Comment by abhishekamralkar** [comment] 2016-02-01 05:54
@erikdw : Thanks . I will try it out the steps .What are your suggestions to do proper cleanup ?

**Comment by dsKarthick** [comment] 2016-02-01 06:07
@abhishekamralkar I was guessing when I said improper cleanup. Upon looking at [this commit](https://github.com/harshach/incubator-storm/commit/a16a95c5e8d889685389607f3a67514b73688e14?w=1) more closely, STORM-130 was fixed by downloading serialized stuff stored in zookeeper if the appropriate directory did not exist.

**Comment by dsKarthick** [comment] 2016-02-01 06:07
@abhishekamralkar What version of strom are you running?

**Comment by abhishekamralkar** [comment] 2016-02-01 06:09
@dsKarthick : I am running `STORM_RELEASE=0.10.0 MESOS_RELEASE=0.25.0`

**Comment by erikdw** [comment] 2016-02-01 06:15
@abhishekamralkar : you'll need to debug this pretty methodically I think.  Are you running in the [vagrant setup](https://github.com/mesos/storm/blob/3376813d8fa0e339c8c0321774e5572eeefb60bb/docs/vagrant.md) that is part of this project?   (I'm trying to figure out which log files I should point you at, but basically you need to look to see what step is actually failing, the `.../stormconf.ser' does not exist` error is assuredly just a symptom of an earlier problem.).

**Comment by abhishekamralkar** [comment] 2016-02-01 06:19
@erikdw : I am running my Mesos CLuster in AWS . If I paste config file here , will it help?

**Comment by dsKarthick** [comment] 2016-02-01 06:22
@erikdw might be right.

@abhishekamralkar Two things
1. How often do you see this error? - Do you see this error all the time when the workers start up?
2. Make sure to grep the logs to find out the first exception.

**Comment by erikdw** [comment] 2016-02-01 06:25
Won't hurt to paste the config, but it's unlikely that I'll spot a specifically bad thing in the configs.  You need to figure out *what* is failing, which involves looking at these logs:
* nimbus
* supervisor
* mesos master
* mesos slave
* mesos executor
* worker

I totally agree with Karthick on both of his points above ^.  Furthermore:
1. do you *ever* see a worker start up successfully?
2. Is this happening with a toy topology that should always succeed no matter what (e.g., the Exclaim Topology in [storm-starter examples](https://github.com/apache/storm/tree/master/examples/storm-starter))?    Can you make the Exclaim Topology work?

**Comment by abhishekamralkar** [comment] 2016-02-01 06:27
@erikdw : Okay I will check out all the logs and paste details here . I am seeing this with all the topologies including the toy topology.

**Comment by erikdw** [comment] 2016-02-01 06:32
@abhishekamralkar : one off-the-top-of-my-head guess is that you might have the wrong URL for the storm-mesos executor tarball.

e.g., for the vagrant setup with the versions you specified, I set it like this:

```
mesos.executor.uri: "file:///usr/local/storm/storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.25.0.tgz"
```

**Comment by abhishekamralkar** [comment] 2016-02-01 06:35
@erikdw I am using this for mesos.executor.uri

```mesos.executor.uri: "file:///tmp/storm.tar.gz"```

**Comment by erikdw** [comment] 2016-02-01 06:42
And you've built from the HEAD of this project's master branch, uploading the resultant `storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.25.0.tgz` file as `/tmp/storm.tar.gz` on the mesos-slave hosts?

**Comment by abhishekamralkar** [comment] 2016-02-01 06:50
@erikdw : Below are the steps I follow

* git clone git@github.com:mesos/storm.git && cd storm
* STORM_RELEASE=0.10.0 MESOS_RELEASE=0.25.0 bin/build-release.sh

Once I got snapshot , I extract it and I change the ```mesos.executor.uri``` path and again compress it and scp to all the slaves at /tmp.

**Comment by dsKarthick** [comment] 2016-02-01 06:50
Zookeeper version? https://groups.google.com/forum/#!topic/storm-user/DcX79-qoSck

**Comment by dsKarthick** [comment] 2016-02-01 06:51
@abhishekamralkar Interesting. Did you check the permissions on the file you copied?

**Comment by abhishekamralkar** [comment] 2016-02-01 06:55
@dsKarthick : Here are my permissions

```-rw-r--r-- 1 ubuntu ubuntu  86M Feb  1 05:05 storm.tar.gz```

**Comment by dsKarthick** [comment] 2016-02-01 06:59
@abhishekamralkar Are you running storm processes as root? If not, do they have permissions to create the directory? I would expect the process to fail with an exception like `permission denied` in case of a permission issue - but just making sure.

**Comment by abhishekamralkar** [comment] 2016-02-01 07:01
Yes I am sunning storm as root user and also deployying toplogies as root user.

**Comment by erikdw** [comment] 2016-02-01 07:01
@abhishekamralkar : how are you running the nimbus?   Manually on some host, or within mesos via marathon or some other meta framework?   I ask because I'm curious about why you say you did this:
> "Once I got snapshot , I extract it and I change the mesos.executor.uri path and again compress it and scp to all the slaves at /tmp."

i.e., that setting is only read by the MesosNimbus, so it's unnecessary to make such a change to the tarball.  You can simply change the `storm.yaml` that is read by the MesosNimbus.

**Comment by abhishekamralkar** [comment] 2016-02-01 07:05
Hmm , so I am runnign it manually ```bin/storm nimbus``` and it is getting registered as Mesos Framework

**Comment by erikdw** [comment] 2016-02-01 07:08
@abhishekamralkar : ok, so another bit of info:  the config file that is read by the MesosSupervisor is supposed to be downloaded from the MesosNimbus's embedded Jetty, the MesosSupervisor / storm worker do not read the config file from within the tarball.  i.e., here's where the config file is added as a file for the mesos executor to download:
* https://github.com/mesos/storm/blob/6a1392a0c1181c227b014cc9c6d8a14fa91cc919/storm/src/main/storm/mesos/MesosNimbus.java#L818

**Comment by dsKarthick** [comment] 2016-02-01 07:13
I already pasted the link, but do take a look at [this link](https://groups.google.com/d/msg/storm-user/DcX79-qoSck/gH8s_j8rSYoJ) where nmartz was involved.

**Comment by abhishekamralkar** [comment] 2016-02-01 07:18
@erikdw : Got it so I am doing something very silly here , what you suggest . I should keep the tar ball in the distribution and run ```storm-mesos nimbus```?

**Comment by abhishekamralkar** [comment] 2016-02-01 07:19
@dsKarthick sure I will take a look.

**Comment by dsKarthick** [comment] 2016-02-01 07:32
@abhishekamralkar I think @erikdw is suggesting a way to avoid extracting the tar for the sake of modifying `mesos.executor.uri ` in storm.yaml. To do that, you will have to do this on master host: Set STORM_CONF_DIR environment variable and run `storm-mesos nimbus`. Because mesos-nimbus distributes the config file to the workers, you could keep the storm.yaml in`/tmp/storm.tar.gz` as is.

**Comment by erikdw** [comment] 2016-02-01 07:36
thanks @dsKarthick : yup, that is what I was suggesting, thanks for digging up the `STORM_CONF_DIR` reference.  To be clear, when you say "on master host", you are simply meaning "on the host where the MesosNimbus is going to run", which in our vagrant setup is indeed called "master", but I don't want there to be any confusion that it needs to be run on a mesos-master host, since that would actually be an anti-pattern for a real cluster.

So, @abhishekamralkar , you simply need to modify `storm.yaml` and then set `STORM_CONF_DIR` to the dir that contains `storm.yaml`.

e.g.,
```
vim /vagrant/storm.yaml
STORM_CONF_DIR=/vagrant bin/storm-mesos nimbus
```

**Comment by dsKarthick** [comment] 2016-02-01 07:50
@erikdw haha. Yeah, thanks for clarifying. @abhishekamralkar Because you mentioned you are running on AWS, do you have any prior experience running storm on mesos? If not, have you tried bringing up vagrant cluster on your local machine. If not, I would strongly recommend getting your local vagrant cluster running in order to gaining some operational experience before trying it on aws.

**Comment by erikdw** [comment] 2016-02-22 08:22
@abhishekamralkar : is this still an issue?

**Comment by erikdw** [comment] 2016-03-07 04:57
Closing for now, @abhishekamralkar please reopen if necessary.

**Closed by erikdw** 2016-03-07 04:57 UTC
Labels: question
